version: '3.8'

services:
  webapi:
   build: webapi
   depends on:
   - mongodb
   ports:
   - 5001:5001


mongodb:
  image: mongo:latest
  environment:
   MONGO_INITDB_ROOT_USERNAME: gbs
   MONGO_INITDB_ROOT_PASSWORD: geheim
  volumes:
   - mongoData:/data/db
volumes:
  mongoData: